(function(){
'use strict';
const PT='pt',EN='en',KEY='yunarunes-language';
const pairs={
'Monstros':'Monsters','Monster Database':'Monster Database','Database':'Database','Team Builder':'Team Builder','Runas':'Runes','Rune Builder':'Rune Builder','Optimizer':'Optimizer','Rune Optimizer':'Rune Optimizer','Códigos':'Codes','Team':'Team',
'Todos os elementos':'All elements','Todas as estrelas naturais':'All natural stars','Todas as estrelas':'All stars','Normais':'Normal','2A — Segundo Despertar':'2A — Second Awakening','Todos':'All','Fogo':'Fire','Água':'Water','Vento':'Wind','Luz':'Light','Trevas':'Dark','Ataque':'Attack','Defesa':'Defense','Suporte':'Support','Abrir':'Open',
'Nome, família ou elemento...':'Name, family or element...','Pesquisar nome, elemento ou estrelas...':'Search name, element or stars...','A carregar os monstros...':'Loading monsters...','A carregar monstros...':'Loading monsters...','A carregar a base...':'Loading database...','A carregar todos os monstros...':'Loading all monsters...','monstros únicos carregados':'unique monsters loaded','monstros únicos':'unique monsters','Nenhum monstro encontrado.':'No monster found.','Não foi possível carregar a base de monstros.':'Could not load the monster database.','Erro ao carregar a base de monstros. Tenta atualizar a página.':'Error loading monster database. Try refreshing the page.','A base não respondeu.':'The database did not respond.','Abrir página do monstro →':'Open monster page →',
'Ferramentas YunaRunes':'YunaRunes Tools','Pesquisa e consulta a base de monstros.':'Search and browse the monster database.','Descobre equipas e sinergias.':'Discover teams and synergies.','Cria builds de runas.':'Build rune sets.','Encontra combinações do inventário.':'Find combinations from your inventory.','YunaRunes para Android':'YunaRunes for Android','Leva as ferramentas contigo no telemóvel.':'Take the tools with you on your phone.','Leva as ferramentas do YunaRunes contigo no telemóvel.':'Take YunaRunes tools with you on your phone.','Instalar / Baixar APK':'Install / Download APK','Baixar APK':'Download APK','Baixar YunaRunes para Android':'Download YunaRunes for Android',
'Pesquisa um monstro e o YunaRunes monta várias opções de equipas respeitando o limite de cada conteúdo.':'Search for a monster and YunaRunes will build several team options while respecting the limit for each content.','Pesquisa um monstro para começar.':'Search for a monster to begin.','Pesquise um monstro':'Search for a monster','Pesquisar um monstro...':'Search for a monster...','Pesquisar um mob e ver com quem combina':'Search a monster and see who it works with','Criar equipas':'Build teams','Ver com quem combina':'See who it works with',
'Arena: máximo 4 mobs por equipa (Ataque ou Defesa).':'Arena: maximum 4 monsters per team (Attack or Defense).','Siege: máximo 3 mobs por equipa (Ataque ou Defesa).':'Siege: maximum 3 monsters per team (Attack or Defense).','WGB: máximo 3 mobs por equipa (Ataque ou Defesa).':'WGB: maximum 3 monsters per team (Attack or Defense).',
'Pesquisa monstros, filtra por elemento e estrelas e abre a ficha individual para ver mais informações.':'Search monsters, filter by element and stars, and open an individual profile for more information.','Monta conjuntos de runas.':'Build rune sets.','Procura as melhores combinações do inventário.':'Find the best combinations from your inventory.','Consulta a utilização dos monstros por conteúdo.':'Check monster usage by content.','Runas recomendadas':'Recommended runes','Substats prioritárias:':'Priority substats:','Projeto independente da comunidade Summoners War':'Independent Summoners War community project','Não afiliado à Com2uS.':'Not affiliated with Com2uS.','Copiar código':'Copy code','Código copiado!':'Code copied!','natural':'natural'
};
const reverse={};Object.keys(pairs).forEach(k=>{if(!reverse[pairs[k]])reverse[pairs[k]]=k});
function current(){try{return localStorage.getItem(KEY)||PT}catch(e){return PT}}
function text(t,lang){const map=lang===EN?pairs:reverse;let s=String(t??'');for(const k of Object.keys(map).sort((a,b)=>b.length-a.length)){if(s.includes(k))s=s.split(k).join(map[k])}return s}
function translateNode(node,lang){if(!node||node.nodeType!==Node.TEXT_NODE)return;if(node.parentElement&&node.parentElement.closest('#language-switcher,script,style,noscript'))return;if(node.__yunaOriginal===undefined)node.__yunaOriginal=node.nodeValue;node.nodeValue=text(node.__yunaOriginal,lang)}
function translateAttrs(el,lang){if(!el||el.nodeType!==Node.ELEMENT_NODE)return;if(el.hasAttribute('placeholder')){if(el.__yunaPH===undefined)el.__yunaPH=el.getAttribute('placeholder');el.setAttribute('placeholder',text(el.__yunaPH,lang))}if(el.hasAttribute('title')){if(el.__yunaTitle===undefined)el.__yunaTitle=el.getAttribute('title');el.setAttribute('title',text(el.__yunaTitle,lang))}if(el.tagName==='OPTION'){if(el.__yunaText===undefined)el.__yunaText=el.textContent;el.textContent=text(el.__yunaText,lang)}}
function scan(root,lang){const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];let n;while((n=walker.nextNode()))nodes.push(n);nodes.forEach(x=>translateNode(x,lang));if(root.querySelectorAll)root.querySelectorAll('input[placeholder],textarea[placeholder],select option,[title]').forEach(x=>translateAttrs(x,lang))}
function active(){document.querySelectorAll('.langbar button[data-lang]').forEach(b=>{const on=b.dataset.lang===current();b.classList.toggle('active',on)});document.querySelectorAll('#language-switcher button[data-lang]').forEach(b=>{const on=b.dataset.lang===current();b.style.background=on?'#35a9e1':'#202a34';b.style.color=on?'#061018':'#fff'})}
function inject(){if(document.querySelector('.langbar')||document.getElementById('yuna-nav-fix'))return;const s=document.createElement('style');s.id='yuna-nav-fix';s.textContent='#language-switcher{position:absolute!important;top:7px;right:10px;z-index:9999!important;display:flex!important;gap:4px;align-items:center;padding:4px!important;background:#111820!important;border:1px solid #2b3742!important;border-radius:9px!important}header.top{padding-right:205px!important}@media(max-width:600px){header.top{padding-right:10px!important}}';document.head.appendChild(s)}
function switcher(){if(document.querySelector('.langbar')||!document.body||document.getElementById('language-switcher'))return;const x=document.createElement('div');x.id='language-switcher';x.innerHTML='<a href="downloads/yunarunes.apk" download title="Baixar YunaRunes para Android">📱 APK</a><button type="button" data-lang="pt">🇧🇷 PT/BR</button><button type="button" data-lang="en">🇬🇧 ENG</button>';x.querySelectorAll('button').forEach(b=>b.style.cssText='cursor:pointer;border:0;border-radius:6px;padding:8px 10px;font-weight:800;font-size:12px;background:#202a34;color:#fff');x.querySelector('a').style.cssText='text-decoration:none;background:#35a9e1;color:#061018;border-radius:6px;padding:8px 10px;font-weight:800;font-size:12px';x.addEventListener('click',function(e){const b=e.target.closest('button[data-lang]');if(!b)return;e.preventDefault();e.stopPropagation();const l=b.dataset.lang===EN?EN:PT;try{localStorage.setItem(KEY,l)}catch(_){}apply(l)},true);(document.querySelector('header.top')||document.body).appendChild(x);active()}
function bindExisting(){document.querySelectorAll('.langbar button[data-lang]').forEach(b=>{if(b.__yunaBound)return;b.__yunaBound=true;b.addEventListener('click',function(e){e.preventDefault();const l=b.dataset.lang===EN?EN:PT;try{localStorage.setItem(KEY,l)}catch(_){}apply(l)})})}
function apply(lang){document.documentElement.lang=lang===EN?'en':'pt-BR';bindExisting();scan(document.body,lang);document.title=text(document.title,lang);active()}
function boot(){inject();switcher();apply(current());if(!window.__yunaLanguageObserver){const ob=new MutationObserver(ms=>{const l=current();ms.forEach(m=>m.addedNodes.forEach(n=>{if(n.nodeType===Node.TEXT_NODE)translateNode(n,l);else if(n.nodeType===Node.ELEMENT_NODE){scan(n,l);translateAttrs(n,l)}});bindExisting()});ob.observe(document.body,{childList:true,subtree:true});window.__yunaLanguageObserver=ob}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();