(function(){
'use strict';
const KEY='yunarunes-language';
const LINKS=[
  ['index.html','Monstros','Monsters'],
  ['database.html','Database','Database'],
  ['team-builder.html','Team Builder','Team Builder'],
  ['runes.html','Runas','Runes'],
  ['optimizer.html','Optimizer','Optimizer']
];
const DICT={
  'Monstros':'Monsters','Monstro':'Monster','Monstros encontrados':'Monsters found','monstros únicos carregados':'unique monsters loaded','Monster Database':'Monster Database',
  'Database':'Database','Team Builder':'Team Builder','Runas':'Runes','Rune Builder':'Rune Builder','Optimizer':'Optimizer','Ferramentas YunaRunes':'YunaRunes Tools','YunaRunes Tools':'YunaRunes Tools',
  'A carregar os monstros...':'Loading monsters...','A carregar a base...':'Loading database...','A carregar inventário...':'Loading inventory...','A carregar perfil do monstro...':'Loading monster profile...',
  'Pesquisa um monstro para começar.':'Search for a monster to get started.','Pesquisar um monstro...':'Search for a monster...','Pesquisar nome, família ou elemento...':'Search name, family or element...','Ex.: Galleon, Camilla, Leo...':'E.g.: Galleon, Camilla, Leo...',
  'Pesquisa monstros, filtra por elemento e estrelas e abre a ficha individual para ver mais informações.':'Search monsters, filter by element and stars, and open the individual page for more information.',
  'Escolhe um monstro e o YunaRunes mostra companheiros dentro do limite desse conteúdo.':'Choose a monster and YunaRunes shows companions within the limit for that content.',
  'Pesquisar um mob e ver com quem combina':'Search a mob and see who it works with','Ver com quem combina':'See who it works with','Criar equipas':'Create teams','Encontrar melhores builds':'Find best builds',
  'Pesquisa um monstro e o YunaRunes monta várias opções de equipas respeitando o limite de cada conteúdo.':'Search for a monster and YunaRunes creates several team options respecting each content limit.',
  'Arena: máximo 4 mobs por equipa (Ataque ou Defesa).':'Arena: maximum 4 mobs per team (Attack or Defense).','Siege: máximo 3 mobs por equipa (Ataque ou Defesa).':'Siege: maximum 3 mobs per team (Attack or Defense).','WGB: máximo 3 mobs por equipa (Ataque ou Defesa).':'WGB: maximum 3 mobs per team (Attack or Defense).',
  'Ataque':'Attack','Defesa':'Defense','Modo':'Mode','Monstro':'Monster','Set de 4':'4-piece set','Set de 2':'2-piece set','Slot 2':'Slot 2','Slot 4':'Slot 4','Slot 6':'Slot 6',
  'Normal — equilibrado':'Normal — balanced','SPD — velocidade':'SPD — speed','DMG — dano':'DMG — damage','EHP — sobrevivência':'EHP — survivability','Qualquer':'Any',
  'Exemplo: Swift + Will exige pelo menos 4 Swift e 2 Will. Se escolheres apenas o set de 4, os outros 2 slots ficam livres.':'Example: Swift + Will requires at least 4 Swift and 2 Will. If you choose only the 4-piece set, the other 2 slots are free.',
  'Stats mínimas':'Minimum stats','Melhores builds':'Best builds','Resultados':'Results','Importar o teu inventário JSON':'Import your JSON inventory','Usar inventário de demonstração':'Use demo inventory','A mostrar as 15 melhores.':'Showing the top 15.','combinações válidas':'valid combinations',
  'Não existem runas suficientes para os filtros escolhidos.':'There are not enough runes for the selected filters.','Nenhuma combinação encontrada. Experimenta baixar os mínimos ou deixar algum set/main stat em “Qualquer”.':'No combination found. Try lowering the minimums or leaving a set/main stat as “Any”.',
  'Usar esta build no Rune Builder':'Use this build in Rune Builder','Inventário de demonstração ativo:':'Demo inventory active:','runas.':'runes.','Inventário personalizado ativo:':'Custom inventory active:','Inventário importado. Agora podes otimizar.':'Inventory imported. You can now optimize.','Inventário de demonstração restaurado.':'Demo inventory restored.',
  'Erro ao carregar o inventário.':'Error loading the inventory.','JSON inválido. Usa um ficheiro de inventário de runas em formato de lista.':'Invalid JSON. Use a rune inventory file in list format.',
  'Escolhe qualquer monstro, elemento e evolução disponível na base. Cada variante usa a fotografia correspondente.':'Choose any monster, element and evolution available in the database. Each variant uses the corresponding image.',
  'Runas recomendadas':'Recommended runes','Sets:':'Sets:','Substats prioritárias:':'Priority substats:','Guardar build':'Save build','Limpar':'Clear','Resumo da build':'Build summary','Estado':'Status','Não guardada':'Not saved','Guardada neste dispositivo':'Saved on this device','Build guardada automaticamente.':'Build saved automatically.','Build limpa.':'Build cleared.',
  'Slots 1–6':'Slots 1–6','Resumo':'Summary','A verificar':'To be checked','Não foi possível carregar os dados deste monstro.':'Could not load this monster\'s data.','Erro ao carregar':'Loading error','Monstro não especificado':'Monster not specified','Monstro não encontrado':'Monster not found',
  'Escolhe um monstro na Monster Database.':'Choose a monster from the Monster Database.','Esta variante ainda não existe na base de dados.':'This variant is not yet in the database.','Voltar à Monster Database':'Back to Monster Database','Voltar à Base de Monstros':'Back to Monster Database',
  'Informações':'Information','Stats base':'Base stats','Skills':'Skills','Despertar':'Awakening','Função':'Role','Elemento':'Element','Estrelas naturais':'Natural stars','Família':'Family','Leader Skill':'Leader Skill','Jogável':'Playable',
  'Perfil individual YunaRunes — variante':'YunaRunes individual profile — variant','Montar Rune Build':'Build Rune Set','Abrir Optimizer':'Open Optimizer','Abrir Rune Builder':'Open Rune Builder',
  'Os stats só são mostrados como valores quando existem dados na base YunaRunes. A evolução para 6★ é diferente da estrela natural do monstro.':'Stats are only shown as values when data exists in the YunaRunes database. Evolving to 6★ is different from the monster\'s natural star grade.',
  'As skills detalhadas deste monstro ainda não estão na base verificada. Não vou inventar descrições.':'Detailed skills for this monster are not yet in the verified database. No descriptions will be invented.',
  'Materiais específicos de despertar ainda não foram adicionados para este monstro.':'Specific awakening materials have not yet been added for this monster.',
  'O despertar pode alterar aparência, nome ou habilidades dependendo do monstro. Os detalhes específicos serão preenchidos apenas quando verificados.':'Awakening may change the appearance, name or skills depending on the monster. Specific details will only be filled in when verified.',
  'Recomendações ainda não verificadas.':'Recommendations not yet verified.','A preencher':'To be filled','Skill':'Skill','Slot':'Slot','Pesos':'Weights',
  'Todos':'All','Todos os elementos':'All elements','Todas as estrelas':'All stars','Todas as estrelas naturais':'All natural stars','Normais':'Normal','2A — Segundo Despertar':'2A — Second Awakening',
  'Nome, família ou elemento...':'Name, family or element...','Abrir página do monstro →':'Open monster page →','Nenhum monstro encontrado.':'No monster found.',
  'Pesquisa e consulta a base de monstros.':'Search and browse the monster database.','Descobre equipas e sinergias.':'Discover teams and synergies.','Cria builds de runas.':'Build rune sets.','Encontra combinações do inventário.':'Find combinations from your inventory.',
  'YunaRunes para Android':'YunaRunes for Android','Leva as ferramentas contigo no telemóvel.':'Take the tools with you on your phone.','Instalar / Baixar APK':'Install / Download APK',
  'O YunaRunes procura combinações reais do inventário, respeitando slots, conjuntos, main stats e requisitos mínimos.':'YunaRunes searches real inventory combinations, respecting slots, sets, main stats and minimum requirements.',
  'A mostrar as 15 melhores.':'Showing the top 15.','unique monsters loaded':'unique monsters loaded','Monstros':'Monsters','Runas':'Runes',
  'RTA':'RTA','Arena':'Arena','Siege':'Siege','PvE':'PvE','Normal':'Normal','Elementos':'Elements','Estrelas':'Stars',
  'Fogo':'Fire','Água':'Water','Vento':'Wind','Luz':'Light','Trevas':'Dark','Ataque':'Attack','Suporte':'Support',
  'Não afiliado à Com2uS.':'Not affiliated with Com2uS.','Projeto independente da comunidade Summoners War':'Independent Summoners War community project'
};
const reverse={};Object.keys(DICT).forEach(k=>{reverse[DICT[k]]=k});
function lang(){try{return localStorage.getItem(KEY)==='en'?'en':'pt'}catch(e){return'pt'}}
function path(){return(location.pathname.split('/').pop()||'index.html').split('?')[0]||'index.html'}
function trText(text,l){const t=String(text??'');if(!t.trim())return t;const map=l==='en'?DICT:reverse;let out=t;for(const k of Object.keys(map).sort((a,b)=>b.length-a.length)){if(out.includes(k))out=out.split(k).join(map[k])}return out}
function translateNode(node,l){if(node.nodeType!==Node.TEXT_NODE)return;if(!node.__yunaOriginal)node.__yunaOriginal=node.nodeValue;const original=node.__yunaOriginal;node.nodeValue=l==='en'?trText(original,'en'):original}
function applyAll(){const l=lang();document.documentElement.lang=l==='en'?'en':'pt-BR';document.querySelectorAll('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===l));
 document.querySelectorAll('title').forEach(t=>{const p=path();const titles={
  'index.html':l==='en'?'YunaRunes — Summoners War Tools':'YunaRunes — Ferramentas Summoners War',
  'database.html':l==='en'?'YunaRunes — Database':'YunaRunes — Database',
  'team-builder.html':l==='en'?'Team Builder — YunaRunes':'Team Builder — YunaRunes',
  'runes.html':l==='en'?'YunaRunes — Rune Builder':'YunaRunes — Rune Builder',
  'optimizer.html':l==='en'?'YunaRunes — Rune Optimizer':'YunaRunes — Rune Optimizer',
  'monster.html':l==='en'?'Monster — YunaRunes':'Monstro — YunaRunes',
  'monster-view.html':l==='en'?'Monster — YunaRunes':'Monstro — YunaRunes'};if(titles[p])t.textContent=titles[p]});
 document.querySelectorAll('input[placeholder],textarea[placeholder]').forEach(e=>{if(!e.__yunaPlaceholder)e.__yunaPlaceholder=e.placeholder;e.placeholder=l==='en'?trText(e.__yunaPlaceholder,'en'):e.__yunaPlaceholder});
 document.querySelectorAll('[title]').forEach(e=>{if(!e.__yunaTitle)e.__yunaTitle=e.getAttribute('title');const v=e.__yunaTitle;e.setAttribute('title',l==='en'?trText(v,'en'):v)});
 const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);const nodes=[];let n;while(n=walker.nextNode())nodes.push(n);nodes.forEach(x=>translateNode(x,l));
 document.querySelectorAll('option').forEach(o=>{if(!o.__yunaText)o.__yunaText=o.textContent;o.textContent=l==='en'?trText(o.__yunaText,'en'):o.__yunaText});
}
function buildHeader(){const headers=[...document.querySelectorAll('header.top')];if(!headers.length)return;const h=headers[0];headers.slice(1).forEach(x=>x.remove());h.querySelectorAll('.mobile-nav').forEach(x=>x.remove());let nav=h.querySelector('nav:not(.mobile-nav)');if(!nav){nav=document.createElement('nav');h.appendChild(nav)}nav.className='nav';nav.innerHTML=LINKS.map(([href,pt,en])=>'<a href="'+href+'" data-i18n-pt="'+pt+'" data-i18n-en="'+en+'">'+(lang()==='en'?en:pt)+'</a>').join('');nav.querySelectorAll('a').forEach(a=>a.classList.toggle('active',(a.getAttribute('href')||'').split('?')[0]===path()));let bar=h.querySelector('.langbar');if(!bar){bar=document.createElement('div');bar.className='langbar';h.appendChild(bar)}bar.innerHTML='<a href="./downloads/yunarunes.apk" download title="Download APK">📱 APK</a><button type="button" data-lang="pt">🇧🇷 PT/BR</button><button type="button" data-lang="en">🇬🇧 ENG</button>';bar.querySelectorAll('[data-lang]').forEach(b=>{b.classList.toggle('active',b.dataset.lang===lang());b.onclick=()=>{try{localStorage.setItem(KEY,b.dataset.lang)}catch(e){}applyAll();buildHeader()}})}
function addCss(){const s=document.getElementById('yuna-header-clean')||document.createElement('style');s.id='yuna-header-clean';s.textContent='header.top{position:sticky!important;top:0!important;z-index:100!important}header.top .mobile-nav{display:none!important}@media(min-width:601px){header.top{display:grid!important;grid-template-columns:1fr auto 1fr!important;align-items:center!important;min-height:64px!important;padding:0 22px!important;gap:0!important}header.top .logo{grid-column:1!important;grid-row:1!important;justify-self:start!important}header.top .nav{grid-column:2!important;grid-row:1!important;display:flex!important;align-items:center!important;justify-content:center!important;gap:18px!important;margin:0!important;white-space:nowrap!important;overflow:visible!important}header.top .langbar{grid-column:3!important;grid-row:1!important;justify-self:end!important;display:flex!important;align-items:center!important;gap:6px!important;margin:0!important}header.top .langbar a,header.top .langbar button{display:inline-flex!important;align-items:center!important;justify-content:center!important;height:40px!important;padding:0 11px!important;border:0!important;border-radius:7px!important;font-size:12px!important;font-weight:900!important;white-space:nowrap!important;text-decoration:none!important;cursor:pointer!important}}@media(max-width:600px){header.top{display:block!important;padding:8px 10px 0!important}header.top .logo{display:block!important;padding:3px 5px 10px!important;font-size:28px!important}header.top .nav{display:grid!important;grid-template-columns:repeat(5,1fr)!important;gap:0!important;margin:0 -10px!important;border-top:1px solid var(--border,#2b3742)!important;padding:8px 3px!important;overflow:visible!important}header.top .nav a{display:flex!important;flex-direction:column!important;align-items:center!important;justify-content:center!important;gap:3px!important;font-size:10px!important;text-align:center!important}header.top .nav a:before{font-size:20px!important;line-height:1!important;color:#5fc7f5!important}header.top .nav a:nth-child(1):before{content:"⌂"}header.top .nav a:nth-child(2):before{content:"▤"}header.top .nav a:nth-child(3):before{content:"⚔"}header.top .nav a:nth-child(4):before{content:"◇"}header.top .nav a:nth-child(5):before{content:"⚙"}header.top .langbar{position:absolute!important;right:8px!important;top:7px!important;display:flex!important;gap:6px!important;align-items:center!important}header.top .langbar a,header.top .langbar button{height:38px!important;padding:0 7px!important;font-size:10px!important}}';if(!s.parentNode)document.head.appendChild(s)}
function boot(){buildHeader();addCss();applyAll();const obs=new MutationObserver(muts=>{if(!obs.busy){obs.busy=true;setTimeout(()=>{applyAll();obs.busy=false},0)}});obs.observe(document.body,{subtree:true,childList:true,characterData:true});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();